#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-unirest-java
Version  : 1.4.9
Release  : 1
URL      : https://repo1.maven.org/maven2/com/mashape/unirest/unirest-java/1.4.9/unirest-java-1.4.9-sources.jar
Source0  : https://repo1.maven.org/maven2/com/mashape/unirest/unirest-java/1.4.9/unirest-java-1.4.9-sources.jar
Source1  : https://repo1.maven.org/maven2/com/mashape/unirest/unirest-java/1.4.9/unirest-java-1.4.9.jar
Source2  : https://repo1.maven.org/maven2/com/mashape/unirest/unirest-java/1.4.9/unirest-java-1.4.9.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-unirest-java-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-unirest-java package.
Group: Data

%description data
data components for the mvn-unirest-java package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/mashape/unirest/unirest-java/1.4.9
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/com/mashape/unirest/unirest-java/1.4.9/unirest-java-1.4.9-sources.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/mashape/unirest/unirest-java/1.4.9
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/mashape/unirest/unirest-java/1.4.9/unirest-java-1.4.9.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/mashape/unirest/unirest-java/1.4.9
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/mashape/unirest/unirest-java/1.4.9/unirest-java-1.4.9.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/mashape/unirest/unirest-java/1.4.9/unirest-java-1.4.9-sources.jar
/usr/share/java/.m2/repository/com/mashape/unirest/unirest-java/1.4.9/unirest-java-1.4.9.jar
/usr/share/java/.m2/repository/com/mashape/unirest/unirest-java/1.4.9/unirest-java-1.4.9.pom
